>>> from pengpengtao.models.models import *
>>> discount = Discount(discount=0.1)
>>> discount
<Discount: Discount object>
>>> discount.save()
>>> t = DealType(content_object=discount)
>>> t.save()
>>> t.content_object
<Discount: Discount object>
>>> deal = Deal(name="1", content=t)
>>> deal.save()
Traceback (most recent call last):
    File "<console>", line 1, in <module>
        File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/base.py", line 460, in save
          self.save_base(using=using, force_insert=force_insert, force_update=force_update)
        File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/base.py", line 553, in save_base
          result = manager._insert(values, return_id=update_pk, using=using)
        File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/manager.py", line 195, in _insert
          return insert_query(self.model, values, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/query.py", line 1436, in insert_query
          return query.get_compiler(using=using).execute_sql(return_id)
      File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/sql/compiler.py", line 791, in execute_sql
          cursor = super(SQLInsertCompiler, self).execute_sql(None)
        File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/models/sql/compiler.py", line 735, in execute_sql
          cursor.execute(sql, params)
        File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/backends/util.py", line 34, in execute
          return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/Django-1.3-py2.7.egg/django/db/backends/sqlite3/base.py", line 234, in execute
          return Database.Cursor.execute(self, query, params)
      IntegrityError: models_deal.begin_time may not be NULL
>>> deal = Deal(name="1", content=t, begin_time=datetime.datetime.now)
Traceback (most recent call last):
File "<console>", line 1, in <module>
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
>>> deal = Deal(name="1", content=t, begin_time='', end_time='')
>>> deal.save()
>>> deal = Deal(name="1", content=t, begin_time='2010-11-12 12:12', end_time='2021-12-12 12:12')
>>> deal.save()
>>> deal.content
<DealType: DealType object>
>>> deal.content.discount
Traceback (most recent call last):
File "<console>", line 1, in <module>
AttributeError: 'DealType' object has no attribute 'discount'
>>> deal.content
<DealType: DealType object>
>>> deal.content.content_object
<Discount: Discount object>
>>> deal.content.content_object.discount
                                                                                                               0.1

